CREATE DATABASE EMPDATA
USE EMPDATA
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE'

-- create PARENT table
CREATE TABLE SALARY (FNAME VARCHAR(25) PRIMARY KEY, BSAL FLOAT, GSAL FLOAT)
INSERT INTO SALARY VALUES ('AAA',5645,1212.26), ('BBB',7456,1999.85),('CCC',5652,1239.14);   ----> PARENT

-- create CHILD table
CREATE TABLE EMP (EMPID INT NOT NULL, FNAME VARCHAR(25), CITY VARCHAR(20) );
INSERT INTO EMP VALUES (101,'AAA','HYD'), (102,'BBB','BLR'),(103,'CCC','GNT');         -----> CHILD

-- adding FOREIGN KEY to child table
ALTER TABLE EMP ADD PRIMARY KEY(EMPID)       ---- adding both primary and foreign key
ALTER TABLE EMP ADD FOREIGN KEY(FNAME) REFERENCES SALARY (FNAME);

-- Check the dtypes
EXEC sp_help 'emp';
SELECT COLUMN_NAME,DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EMP'

-- INSERTING INTO CHILD TABLE
INSERT INTO EMP VALUES (106,'HHH','GNT')

-- INSERTING INTO PARENT TABLE
INSERT INTO SALARY VALUES ('HHH',5125,6531.21)

SELECT * FROM SALARY --> PARENT                  ----> If HHH is present in parent table... then the HHH record can be inserted into child table

-- DELETE HHH FROM PARENT TABLE
DELETE FROM SALARY WHERE FNAME = 'HHH'

-- DELETE HHH FROM CHILD TABLE
DELETE FROM EMP WHERE FNAME = 'HHH'


SELECT * FROM SALARY
SELECT * FROM EMP
EXEC sp_help 'emp';

-- Drop the FOREIGN KEY Constraint
ALTER TABLE EMP DROP CONSTRAINT FK__EMP__FNAME__398D8EEE