USE sampledb

select table_name from INFORMATION_SCHEMA.TABLES where table_type = 'Base Table'

CREATE TABLE IPL
(tno int NOT NULL, tname varchar(25), caption varchar(15), coach varchar(15)) 

INSERT INTO IPL VALUES(1,'KOLKATA KNIGHT RIDERS','GANGULY','JOHNRIGHT')
INSERT INTO IPL VALUES(2,'DECCAN CHARGES','LAXMAN','AKRAM')
INSERT INTO IPL VALUES(3,'RAYOL CHALANGERS BANGALOR','DRAVID','KUMBLE')
INSERT INTO IPL VALUES(4,'PUNE WARRIERS','YOURAJ SINGH','KIRSTEN') 
INSERT INTO IPL VALUES(5,'MUMBAI INDIANS','SACHIN','AJARUDDIN')

SELECT * FROM IPL
INSERT INTO IPL VALUES(1,'RAJASTHAN ROYALS','HARBAJAN SINGH','WARN')

--ERROR:-
INSERT INTO IPL VALUES(NULL,'DELHI DARE DEVILIS','SEHWAG','MIYANDAD')
--ERROR:-
INSERT INTO IPL(TNAME,CAPTION,COACH)
VALUES('KOCHI TUSKERS','GANGULY','KAPIL DEV')


ALTER TABLE IPL
ALTER COLUMN TNAME VARCHAR(25) NOT NULL

--ERROR:-
INSERT INTO IPL(TNO,CAPTION,COACH)
VALUES(1,'DHONI','CHAPEL')

INSERT INTO IPL
VALUES(1,'CHENNAI','DHONI','CHAPEL')

DROP TABLE IPL
------------------------------------------
------------------------------------------

CREATE TABLE IPL
(tno int, tname varchar(25), caption varchar(15), coach varchar(15)) 

INSERT INTO IPL VALUES(1,'KOLKATA KNIGHT RIDERS','GANGULY','JOHNRIGHT')
INSERT INTO IPL VALUES(2,'DECCAN CHARGES','LAXMAN','AKRAM')
INSERT INTO IPL VALUES(3,'RAYOL CHALANGERS BANGALOR','DRAVID','KUMBLE')
INSERT INTO IPL VALUES(4,'PUNE WARRIERS','YOURAJ SINGH','KIRSTEN')
INSERT INTO IPL VALUES(5,'MUMBAI INDIANS','SACHIN','AJARUDDIN')

SELECT * FROM IPL
INSERT INTO IPL VALUES(1,'RAJASTHAN ROYALS','HARBAJAN SINGH','WARN')


--ERROR:-
ALTER TABLE IPL
ADD CONSTRAINT UQ1 UNIQUE(TNO)
SELECT * FROM IPL

DELETE FROM IPL
WHERE TNAME='RAJASTHAN ROYALS'
ALTER TABLE IPL
ADD CONSTRAINT UQ1 UNIQUE(TNO)
--ERROR:-
INSERT INTO IPL
VALUES(2,'PANJAB TIGERS','GABBAR SINGH','MANMOHAN SINGH')

sp_help ipl

ALTER TABLE IPL
DROP CONSTRAINT UQ1

DROP TABLE IPL
--------------------------------------------------
--------------------------------------------------
--PRIMARY KEY

CREATE TABLE IPL
(tno int, tname varchar(25), caption varchar(15), coach varchar(15)) 

INSERT INTO IPL VALUES(1,'KOLKATA KNIGHT RIDERS','GANGULY','JOHNRIGHT')
INSERT INTO IPL VALUES(2,'DECCAN CHARGES','LAXMAN','AKRAM')
INSERT INTO IPL VALUES(3,'RAYOL CHALANGERS BANGALOR','DRAVID','KUMBLE')
INSERT INTO IPL VALUES(4,'PUNE WARRIERS','YOURAJ SINGH','KIRSTEN')
INSERT INTO IPL VALUES(5,'MUMBAI INDIANS','SACHIN','AJARUDDIN') 
INSERT INTO IPL VALUES(NULL,'CHENNAI','DHONI','KRISHNA')

SELECT * FROM IPL

--ADD CONSTRAINT INTO COLUMN LEVEL
--ERROR:-
ALTER TABLE IPL
ADD CONSTRAINT PK1 PRIMARY KEY(TNO)
--ERROR:-
ALTER TABLE IPL
ALTER COLUMN TNO INT NOT NULL
SELECT * FROM IPL

UPDATE IPL
SET TNO=6
WHERE TNAME='CHENNAI'

ALTER TABLE IPL
ALTER COLUMN TNO INT NOT NULL

ALTER TABLE IPL
ADD CONSTRAINT PK1 PRIMARY KEY(TNO)

SELECT * FROM IPL
--ERROR:-
INSERT INTO IPL VALUES(5,'DDD','SEHWAG','CHAPEL')

--DROPPING CONSTRAINT
ALTER TABLE IPL
DROP CONSTRAINT PK1

DROP TABLE IPL
-------------------------------------------------------------
-------------------------------------------------------------
--DEFAULT

--Duplicate specifies what values are stored in a column 
--if we do not specify a value for the column when inserting a row/record
--EXAMPLE 1:-
CREATE TABLE emp
(empno char(4) PRIMARY KEY, ename varchar(10), sal numeric(10,2), gen char(1) DEFAULT'M')
sp_help 'emp'

INSERT INTO EMP(EMPNO,ENAME,SAL)
VALUES(1111,'KRISHNA',7000)

SELECT * FROM EMP
INSERT INTO EMP VALUES(2222,'RAMA',9000,'M')

--ERROR:-
INSERT INTO EMP VALUES(3333,'ANJI',5000,'MALE')


--EXAMPLE 2:-
CREATE TABLE PROD
(pno int, 
pname varchar(10),
mfg date DEFAULT getdate() not null, 
exp date DEFAULT dateadd(yy,2,getdate()))


INSERT INTO PROD(PNO,PNAME)
VALUES(1,'BRITANIA')
INSERT INTO PROD(PNO,PNAME)
VALUES(2,'GOODDAY')

SELECT * FROM PROD
DROP TABLE PROD

select dateadd(mm,4,dateadd(y,5,dateadd(yy,2,getdate()) ) )
----------------------------------------------------------------
----------------------------------------------------------------
----------------------------------------------------------------
--CHECK

CREATE TABLE emp
(empno char(4), ename varchar(10),
sal numeric(10,2)CHECK(sal BETWEEN 1000 AND 5000)) 

INSERT INTO EMP VALUES(1111,'KRISHNA',3000)
INSERT INTO EMP VALUES(2222,'RAMA',5000)
INSERT INTO EMP VALUES(3333,'RAJA',6000) ---> execute later

select * from emp

alter table emp drop constraint CK__emp__sal__3BFFE745 --DROP CHECK constraint

alter table emp add constraint C1 check (sal between 1000 and 5000)
sp_help emp

drop table emp

